name: online_image_classification
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  image_picker: ^1.1.2
  camera: ^0.10.6
  # todo-01: add dependency
  http: ^1.2.2
  image: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
